# Generated by Django 5.2.1 on 2025-05-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=70, null=True)),
                ('image', models.CharField(max_length=100)),
                ('create_date', models.DateField()),
                ('expire_date', models.DateField()),
                ('country', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(choices=[('fruits', 'fruits'), ('vegtables', 'vegtables'), ('Dairy', 'Dairy'), ('baked goods', 'baked goods')], max_length=50)),
            ],
        ),
    ]
